In [174]:
# https://www.kaggle.com/code/gennadylaptev/qwk-loss-for-pytorch/notebook

In [175]:
import numpy as np
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# def kappa_loss(
#     p: torch.tensor, y: torch.tensor, n_classes: int = 3, eps: float = 1e-10
# ) -> float:
#     """
#     QWK loss function as described in https://arxiv.org/pdf/1612.00775.pdf

#     Arguments:
#         p: a tensor with probability predictions, [batch_size, n_classes],
#         y, a tensor with one-hot encoded class labels, [batch_size, n_classes]
#     Returns:
#         QWK loss
#     """

#     W = np.zeros((n_classes, n_classes))
#     for i in range(n_classes):
#         for j in range(n_classes):
#             W[i, j] = (i - j) ** 2

#     W = torch.from_numpy(W.astype(np.float32)).to(device)

#     O = torch.matmul(y.t(), p)
#     E = torch.matmul(y.sum(dim=0).view(-1, 1), p.sum(dim=0).view(1, -1)) / O.sum()

#     return (W * O).sum() / ((W * E).sum() + eps)


def kappa_loss(p, y, n_classes=3, eps=1e-10):
    """
    QWK loss function as described in https://arxiv.org/pdf/1612.00775.pdf

    Arguments:
        p: a tensor with probability predictions, [batch_size, n_classes],
        y, a tensor with one-hot encoded class labels, [batch_size, n_classes]
    Returns:
        QWK loss
    """

    W = np.zeros((n_classes, n_classes))
    for i in range(n_classes):
        for j in range(n_classes):
            W[i, j] = (i - j) ** 2

    W = torch.from_numpy(W.astype(np.float32)).to(device)

    O = torch.matmul(y.t(), p)
    E = torch.matmul(y.sum(dim=0).view(-1, 1), p.sum(dim=0).view(1, -1)) / O.sum()

    return (W * O).sum() / ((W * E).sum() + eps)

In [176]:
test_p = torch.tensor([[0.0, 0.0, 1.0]])
test_y = torch.tensor([[1.0, 0.0, 0.0]])

kappa_loss(test_p, test_y)

tensor(1.)

In [207]:
test_p = torch.tensor([[1.0, 0.0, 0.0]])
test_y = torch.tensor([[1.0, 0.0, 0.0]])

print(kappa_loss(test_p, test_y))

test_p = torch.tensor([[0.0, 1.0, 0.0]])
test_y = torch.tensor([[1.0, 0.0, 0.0]])

print(kappa_loss(test_p, test_y))

test_p = torch.tensor([[0.0, 0.0, 1.0]])
test_y = torch.tensor([[1.0, 0.0, 0.0]])

print(kappa_loss(test_p, test_y))

tensor(0.)
tensor(1.)
tensor(1.)


In [208]:
test_p = torch.tensor([[1.0, 0.0, 0.0]])
test_y = torch.tensor([[0.60, 0.30, 0.10]])

print(kappa_loss(test_p, test_y))

test_p = torch.tensor([[0.0, 1.0, 0.0]])
test_y = torch.tensor([[0.60, 0.30, 0.10]])

print(kappa_loss(test_p, test_y))

test_p = torch.tensor([[0.0, 0.0, 1.0]])
test_y = torch.tensor([[0.60, 0.30, 0.10]])

print(kappa_loss(test_p, test_y))

test_p = torch.tensor([[0.60, 0.30, 0.10]])
test_y = torch.tensor([[0.60, 0.30, 0.10]])

print(kappa_loss(test_p, test_y))

tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)


In [179]:
type(test_p)

torch.Tensor

In [180]:
torch.randn(3)

tensor([ 0.6078, -1.3214,  0.8973])

In [181]:
tensor1 = torch.tensor([[2, 1, 0], [1, 2, 0]])
tensor2 = torch.tensor([[1, 1, 2], [1, 1, 2]])

torch.matmul(tensor1.t(), tensor2)

tensor([[3, 3, 6],
        [3, 3, 6],
        [0, 0, 0]])

In [182]:
tensor1 = torch.tensor(
    [
        [0.0, 1.0, 0.0],
        # [1.0, 0.0, 0.0]
    ]
)
tensor2 = torch.tensor(
    [
        [0.0, 1.0, 0.0],
        # [1.0, 0.0, 0.0]
    ]
)

torch.matmul(tensor1.t(), tensor2)

tensor([[0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]])

In [183]:
tensor1 = torch.tensor([[0.3, 0.6, 0.1], [0.4, 0.2, 0.4]])
tensor2 = torch.tensor([[0.0, 1.0, 0.0], [1.0, 0.0, 0.0]])

torch.matmul(tensor1.t(), tensor2)
# 行: 予測
# 列: 正解
# 例えば、1列目は、正解が1の時、予測確率はそれぞれ0.4, 0.2, 0.4であることを表す。

tensor([[0.4000, 0.3000, 0.0000],
        [0.2000, 0.6000, 0.0000],
        [0.4000, 0.1000, 0.0000]])

In [184]:
tensor1 = torch.tensor([[1.0, 0.0, 0.0], [1.0, 0.0, 0.0]])
tensor2 = torch.tensor([[0.0, 1.0, 0.0], [0.0, 1.0, 0.0]])

torch.matmul(tensor2.sum(dim=0).view(-1, 1), tensor1.sum(dim=0).view(1, -1))

tensor([[0., 0., 0.],
        [4., 0., 0.],
        [0., 0., 0.]])

In [185]:
tensor1 = torch.tensor([[1.0, 0.0, 0.0], [1.0, 0.0, 0.0]])
tensor2 = torch.tensor([[0.0, 1.0, 0.0], [0.0, 1.0, 0.0]])

torch.matmul(tensor2.sum(dim=0).view(-1, 1), tensor1.sum(dim=0).view(1, -1))

tensor([[0., 0., 0.],
        [4., 0., 0.],
        [0., 0., 0.]])

In [186]:
tensor2.sum(dim=0).view(-1, 1)

tensor([[0.],
        [2.],
        [0.]])

In [187]:
tensor1.sum(dim=0).view(1, -1)

tensor([[2., 0., 0.]])

In [188]:
torch.matmul(tensor2.sum(dim=0).view(-1, 1), tensor1.sum(dim=0).view(1, -1))

tensor([[0., 0., 0.],
        [4., 0., 0.],
        [0., 0., 0.]])

In [189]:
from sklearn.metrics import cohen_kappa_score

cohen_kappa_score([1, 2, 3], [1, 2, 3])

1.0

In [190]:
cohen_kappa_score([1, 1, 3], [1, 2, 3])

0.5

In [191]:
cohen_kappa_score([1, 2, 2], [1, 2, 3])

0.5

In [192]:
cohen_kappa_score([0.0, 1.0, 0.0], [0.0, 0.0, 1.0])

-0.5

In [193]:
cohen_kappa_score([1, 2, 3], [1, 2, 3])

1.0

In [194]:
cohen_kappa_score([2, 2, 3], [1, 2, 3])

0.5

In [195]:
cohen_kappa_score([3, 2, 3], [1, 2, 3])

0.5

In [196]:
cohen_kappa_score([1, 2, 2], [1, 2, 3])

0.5

In [197]:
cohen_kappa_score([2, 1, 1], [1, 2, 3])

-0.5

In [198]:
cohen_kappa_score([1, 2, 1], [1, 2, 3])

0.5

In [199]:
cohen_kappa_score([1, 2, 3], [1, 2, 3])

1.0

In [200]:
cohen_kappa_score([1, 3, 2], [1, 2, 3])

0.0

In [201]:
cohen_kappa_score([3, 1, 2], [1, 2, 3])

-0.5

In [202]:
cohen_kappa_score([3, 2, 1], [1, 2, 3])

0.0